---
title: "Drift detection on continuous time series"
author: "QUERNE Simon"
date: '2023-12-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
n = 100
n_ann = 5
N = n*n_ann

x = rnorm(N, 500, 40) # Génère les valeurs
S = n_ann*365 # Nombre d'emplacements
s_i = sort(sample(S, N, replace=TRUE)) # Attribue les valeurs aux emplacements
t_ano = seq(N/2, N/2 + N/5)
x[t_ano] = x[t_ano] + 50 # Crée l'anomalie
plot(s_i, x, ylim=c(0, max(x)*1.1), pch=20, col='#00000088')
abline(v=c(s_i[t_ano[1]], s_i[tail(t_ano, 1)]), lty=2, col='red')
```
```{r}
test_data = data.frame(x=x, s=s_i)
get_window = function(z, s, h) abs(z - s) <= h
```

```{r}
Like = function(data, bandwidth) {
  X = sum(data$x)
  N = nrow(data)
  mu = X/N
  sig2 = var(data$x)
  
  s_vect = unique(data$s)
  
  LLR = sapply(
    s_vect,
    function(z0) {
      in_window = get_window(z0, data$s, bandwidth)
      window_split = split(data, in_window)
      data.in = window_split[['TRUE']]
      data.out = window_split[['FALSE']]
      
      x_z = sum(data.in$x)
      n_z = nrow(data.in)
      
      mu_z = x_z/n_z
      la_z = (X - x_z)/(N - n_z)
      
      sig_in = sum(data.in$x^2) - 2*x_z*mu_z + n_z*mu_z^2 # Variance sur la fenêtre
      sig_out = sum(data.out$x^2) - 2*(X-x_z)*la_z + (N-n_z)*la_z^2 # Hors de la fenêtre
      sig2_z = (sig_in + sig_out)/N # Variance commune du modèle avec anomalie
      
      LLR_z = N*log(sqrt(sig2)) - N*log(sqrt(sig2_z))
      
      return(LLR_z)
    }
  )
  
  max_idx = which.max(LLR)
  max_loc = s_vect[max_idx]
  T_stat = max(LLR)
  return(list('T_stat'=T_stat, 'max_loc'=max_loc))
}

shuffle_Like = function(data, bandwidth, M=100){
  T_1 = Like(data, bandwidth)
  T_M = lapply(
    1:M,
    function(m) {
      shuffled_data = data
      shuffled_data$s = sample(shuffled_data$s, nrow(data))
      return(Like(shuffled_data, bandwidth))
    }
  )
  all_T = sapply(T_M, function(l) l$T_stat)
  R = rank(c(T_1$T_stat, all_T))[1]
  T_1[['R']] = R
  T_1[['p-value']] = R/(M+1)
  return(T_1)
}
```


```{r}
h = S/(4*1:3)
#sapply(h, function(h0) Like(x, s, bandwidth=h0))
listlist = sapply(h, function(h0) shuffle_Like(test_data, h0, 100))
```

```{r}
j = which.max(listlist['T_stat',])
h0 = h[j]
cluster_center = listlist[, j][['max_loc']]
in_cluster = abs(s_i - cluster_center) <= h0

x_in = x[in_cluster]
s_in = s_i[in_cluster]

x_out = x[!in_cluster]
s_out = s_i[!in_cluster]

mu_in = mean(x_in)
mu_out = mean(x_out)

plot(
  s_in,
  x_in,
  xlim=quantile(s_i, 0:1),
  ylim=c(0, max(x)*1.1),
  pch=20,
  col='#FF000044',
  main='Application aux données test',
  sub=paste('Taille de fenêtre', h0, sep=': '),
  xlab='Emplacements',
  ylab='Valeurs'
)

points(
  s_out,
  x_out,
  pch=20,
  col='#00000044'
)

abline(v=c(s_i[t_ano[1]], s_i[tail(t_ano, 1)]), lty=2, col='red', lwd=1)

cluster_start = s_i[which(in_cluster)[1]]
cluster_end = s_i[tail(which(in_cluster), 1)]

segments(x0=c(1, cluster_end), x1=c(cluster_start, tail(s_i, 1)), y0=mu_out, col='black', lty=1)
segments(x0=cluster_start, x1=cluster_end, y0=mu_in, col='red', lty=1)
```

